"""add workout_type to activities

Revision ID: d42afc89146d
Revises: b136f87004a8
Create Date: 2026-01-17 23:54:58.669782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42afc89146d'
down_revision: Union[str, Sequence[str], None] = 'b136f87004a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('workout_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'workout_type')
    # ### end Alembic commands ###
