"""add profile pictures to users

Revision ID: e8f747b0f8da
Revises: d42afc89146d
Create Date: 2026-01-18 17:09:17.560099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f747b0f8da'
down_revision: Union[str, Sequence[str], None] = 'd42afc89146d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_medium', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_medium')
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
